version: '2'

services:
  owncloud:
    image: owncloud
    ports:
      - '8080:80'
    links:
      - db
  db:
    build: ./db
    expose:
      - '3306'
    volumes_from:
      - secrets
    entrypoint: /secrets-entrypoint.sh
  secrets:
    image: thegene/mounted-secrets
    volumes:
      - /secrets
      - ${ENCRYPTED_SECRETS_MOUNT_PATH}:/encrypted
      - ${KEY_MOUNT_PATH}:/keys
    environment:
      - SECRETS_PASSPHRASE


volumes:
  secrets:
