version: '2'

services:
  owncloud:
    image: owncloud
    ports:
      - '8080:80'
    links:
      - db
  db:
    image: thegene/mariadb-with-secrets
    expose:
      - '3306'
    volumes:
      - ${SECRETS_HOST_PATH}:/secrets
